---
platform:
  - 'baremetal'

is_bootloader:
  - 'true'

cflags:
  global:
     - '-Os'
     - '-Wno-analyzer-allocation-size'
     - '-Wno-analyzer-null-dereference'
     - '-Wno-analyzer-infinite-loop'
     - '-Wno-analyzer-use-of-uninitialized-value'
     - '-Wno-analyzer-shift-count-overflow'

linker:
  script: mpfs-envm
